### ISSUE TITLE
Links from CPAN are broken

### ISSUE THREAD

**Issue by rrthomas** [shlomif/perl-Test-RunValgrind#1]
I tried to file a bug by following the link from CPAN, which gives a 404 on GitHub.

**Comment by shlomif** [comment]
Hi!

On Fri, 12 Jan 2018 13:12:48 +0000 (UTC)
Reuben Thomas <notifications@github.com> wrote:

> I tried to file a bug by following the link from CPAN, which gives a 404 on
> GitHub.
> 

where is the page with the link, and what is the link's caption?

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Free (Creative Commons) Music Downloads, Reviews and more - http://jamendo.com/

Bill Gates, CEO of Microsoft decides to use Richard Stallman’s Emacs as the
basis of his company’s state‐of‐the‐art product Microsoft Editing Macros™
Enterprise Edition XP .NET Professional.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by rrthomas** [comment]
https://metacpan.org/pod/Test::RunValgrind links from "Issues" to https://github.com/shlomif/test-runvalgrind/issues

**Comment by shlomif** [comment]
Should be fixed in 0.0.3. Thanks!
