### ISSUE TITLE
Apparently missing dependency on Test::Trap

### ISSUE THREAD

**Issue by rrthomas** [shlomif/perl-Test-RunValgrind#2]
When I run

`cpan Test::RunValgrind`

I get an error about `Test::Trap` not being installed. Shouldn't this be a dependency? (Sorry if I misunderstood something, I'm not a Perl expert!

**Comment by rrthomas** [comment]
Certainly when I install Test::Trap, `cpan Test::RunValgrind` works fine, and normally `cpan` seems to install required dependencies…

**Comment by rrthomas** [comment]
In fact, I think this problem is the same as issue #3: I see that `Test::Trap` ends up installed in the same wrong location. I installed it via Ubuntu.

**Comment by shlomif** [comment]
Closing. See http://perl-begin.org/topics/cpan/
