### ISSUE TITLE
Does not install on my PERL5LIB

### ISSUE THREAD

**Issue by rrthomas** [shlomif/perl-Test-RunValgrind#3]
After installing `Test::RunValgrind` with `cpan`, it was still not found in my `@INC`.

I run cpan in my home directory; my `PERL5LIB` is:

    /home/rrt/.local/x86_64-linux-gnu-thread-multi/lib/perl/5.22.1:/home/rrt/.local/share/perl

(This is constructed from my home directory, arch and the current Perl version, obviously.)

For some reason, `Test::RunValgrind` installs itself under `/home/rrt/.local/lib/perl5` (module) and `/home/rrt/.local/lib/perl5/x86_64-linux-gnu-thread-multi` (tests). Again, I'm not a Perl expert, but no other module I have downloaded from CPAN has done this.

**Comment by rrthomas** [comment]
Manually copying `Test/RunValgrind.pm` into `/home/rrt/.local/share/perl/5.22.1` seems to install it correctly.

**Comment by rrthomas** [comment]
I just tested that my setup is not somehow broken by running `cpan Net::SFTP`, and that worked fine, installing in the expected location.

**Comment by shlomif** [comment]
On Fri, 12 Jan 2018 13:41:37 +0000 (UTC)
Reuben Thomas <notifications@github.com> wrote:

> I just tested that my setup is not somehow broken by running `cpan
> Net::SFTP`, and that worked fine, installing in the expected location.
> 

Dear Ruben,

please test that your set-up is compatible with
https://metacpan.org/pod/Module::Build and perhaps use
https://metacpan.org/pod/local::lib or perlbrew or whatever. This does not seem
like a problem with the packaging itself and seems like a
https://en.wiktionary.org/wiki/PEBKAC . If you need further assistance with
using perl, see the resources at http://perl-begin.org/ .

-- Shlomi

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
List of Text Processing Tools - http://shlom.in/text-proc

But if you’re writing [open source software] for the world, you have to listen
to your customers — this doesn’t change just because they’re not paying you in
money.
    — Eric S. Raymond in The Cathedral and the Bazaar

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by rrthomas** [comment]
As you can see, I tried to rule out a PEBKAC by testing another module; also note I've had no problem with this setup with dozens of other CPAN modules.

I looked at the documentation for Module::Build, but I can't see anything about how to test my setup for compatibility with it, or what that would mean. I had a look at the documentation for local::lib, but it's unclear to me what it would bring to the situation; in any case, it would force me to reinstall all the (perfectly working) CPAN modules I already have installed.

As I said in the original report, the obvious problem is that Test::RunValgrind is installing itself in a location that is not on my PERL5LIB (it seems to be reversing two directories).

**Comment by rrthomas** [comment]
I tried grepping through the build directory for my home directory `/home/rrt`, and all the paths I can find there are correct. In particular, in the `Build` script, it correctly lists the components of my `PERL5LIB`.

**Comment by rrthomas** [comment]
I notice from looking at timestamps that `Module::Build` installed itself in the desired place (on my `PERL5LIB`) as part of the installation of `Test::RunValgrind` (which itself went to the wrong place). `Path::Tiny` also was installed in the right place, while `Test::Trap` was installed in the wrong place along with `Test::RunValgrind`. Does that give a clue as to what is going on?

**Comment by rrthomas** [comment]
OK, as far as I can see, this comes from the CPAN default settings being different from the Module::Build default settings.

CPAN default: `INSTALLDIRS=site PREFIX=/home/rrt/.local INSTALLSITEARCH=/home/rrt/.local/].$Config{archname}.q[/lib/perl/].$Config{version}` (this is from my `.cpan/CPAN/MyConfig.pm`, which I am pretty sure I have never edited).

Module::Builder default: 

           my %config = (
               installprivlib  => $lib,
               installsitelib  => $lib,
               installarchlib  => "$lib/$Config{archname}",
               installsitearch => "$lib/$Config{archname}"
           );

(from `Build/Compat.pm`; at least, I can't find any other place where e.g. `installsitearch` is set).

So, it looks like I can either add `Module::Build`'s default location to my `PERL5LIB`, or I can reconfigure CPAN, and change my `PERL5LIB`…

**Comment by shlomif** [comment]
Closing then. Not a problem with this project.

**Comment by rrthomas** [comment]
OK, I've reconfigured CPAN and now I've got everything in the same place and placated Module::Build. I have to say, its defaults are saner than the old MakeMaker ones, in any case.

**Comment by shlomif** [comment]
On Fri, 12 Jan 2018 17:11:33 +0000 (UTC)
Reuben Thomas <notifications@github.com> wrote:

>  OK, I've reconfigured CPAN and now I've got everything in the same place and
> placated Module::Build. I have to say, its defaults are saner than the old
> MakeMaker ones, in any case.
> 

nice.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Stop Using MSIE - http://www.shlomifish.org/no-ie/

Real programmers use a nice editor and a nice programming language and get it
done in less than O(N!).
    — vanguard on Freenode’s ##programming

Please reply to list if it's a mailing list post - http://shlom.in/reply .
