### ISSUE TITLE
Please make it possible to add arguments  to valgrind

### ISSUE THREAD

**Issue by rrthomas** [shlomif/perl-Test-RunValgrind#4]
For example, it's useful to be able to run it with `--leak-check=full --show-leak-kinds=all`.

(It is easy enough to edit the source of `RunValgrind.pm` to achieve this, but not very hygienic!)

**Comment by shlomif** [comment]
On Mon, 15 Jan 2018 23:18:40 +0000 (UTC)
Reuben Thomas <notifications@github.com> wrote:

> For example, it's useful to be able to run it with `--leak-check=full
> --show-leak-kinds=all`.
> 
> (It is easy enough to edit the source of `RunValgrind.pm` to achieve this,
> but not very hygienic!
> 

sounds like a useful feature.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Star Trek: “We, the Living Dead” - http://shlom.in/st-wtld

/usr/bin/perl consults Chuck Norris with how to parse Perl.
    — Nadav Vinik ; http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Implemented in v0.2.0 - closing. Thanks!
